### ISSUE TITLE
travis-CI

### ISSUE THREAD

**Issue by dave-wind** [calebman/vue-DBM#3]
```
请问一下 你的 自动部署 页面js路径 是如何 /vue-DBM/static/...js  这样的  
我现在都是/static/..js  显示404 谢谢

**Comment by calebman** [comment]
config/index.js文件中的assetsPublicPath配置由
assetsPublicPath:''更改为assetsPublicPath:'/'
这样npm run build打包后生成的index.html里面js的所有相对路径会变为/static/XXX.js
如果没有前面这条斜杠即static/XXX.js这样的路径浏览器会默认只加上域名前缀，少了项目名这个二级地址所以找不到js报了404
