### ISSUE TITLE
优化建议：渲染动画

### ISSUE THREAD

**Issue by wencaizhang** [calebman/vue-DBM#6]
对应的笔记链接：[用户体验](https://github.com/calebman/vue-DBM/blob/master/docs/package.md#6-%E7%94%A8%E6%88%B7%E4%BD%93%E9%AA%8C)

建议将渲染（loading）动画直接放在 `#app` 内部，当 `App.vue` 挂载的时候会直接清空 `#app` 内原有的 DOM 元素，就无需手动移除了。

```html
<body>
  <div id="app">
    <div id="system-loading" class="showbox"></div>
  </div>
</body>
```

**Comment by calebman** [comment]
好的非常感谢

**Comment by wwggxx** [comment]
这是来自叶落终归根╮的回复：你好，你的邮件我已收到。
